[package]
name = "dustdata"
version = "1.1.0"
edition = "2021"
description = "A data concurrency control storage engine to Rustbase"
repository = "https://github.com/rustbase/dustdata"
homepage = "https://github.com/rustbase/dustdata"
authors = ["Rustbase"]
license = "MIT"
exclude = [
    "test_data/*",
    "README.md",
    "CONTRIBUTING.md",
    ".editorconfig",
]


[dependencies]
bson = "2.4.0"
hex = "0.4.3"
lz4 = "1.24.0"
farmhash = "1.1.5"
bitvec = "1.0.1"
ctrlc = {version = "3.2.3", features = ["termination"]}
serde = {version = "1.0.148", features = ["derive"]}
chrono = "0.4.23"