[package]
name = "dustdata"
version = "0.2.7"
edition = "2021"
description = "A data concurrency control storage engine to Rustbase"
repository = "https://github.com/rustbase/dustdata"
homepage = "https://github.com/rustbase/dustdata"
authors = ["Rustbase"]
license = "MIT"
exclude = [
    "test_data/*",
    "README.md",
    "CONTRIBUTING.md",
    ".editorconfig",
]


[dependencies]
bson = "2.4.0"
hex = "0.4.3"
lzzzz = "1.0.3"
fasthash = "0.4.0"
bitvec = "1.0.1"