[package]
name = "dustdata"
version = "0.1.0"
edition = "2021"
exclude = [
    "test_data/*",
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.2.0"
rand = "0.8.5"
hex = "0.4.3"
lzzzz = "1.0.3"
chrono = "0.4.19"
rbtree = "0.1.5"