[package]
name = "dustdata"
version = "0.1.0"
edition = "2021"
description = "A data concurrency control storage engine to Rustbase"
license = "MIT"
exclude = [
    "test_data/*",
]


[dependencies]
bson = "2.2.0"
rand = "0.8.5"
hex = "0.4.3"
lzzzz = "1.0.3"
chrono = "0.4.19"
rbtree = "0.1.5"